from datetime import datetime


def generate_html(data, filename="webshield_report"):

    score = data.get("score", 0)

    rating = data.get(
        "rating",
        "UNKNOWN"
    )


    if score >= 80:
        color = "#00ff88"

    elif score >= 60:
        color = "#ffaa00"

    else:
        color = "#ff4444"



    html = f"""

<!DOCTYPE html>

<html>

<head>

<title>WebShield 2.0 Report</title>


<style>

body {{

background:#080b12;
color:#ffffff;
font-family:Segoe UI,Arial;
padding:30px;

}}


.container {{

max-width:1100px;
margin:auto;

}}


.header {{

background:linear-gradient(135deg,#00d9ff,#005bea);
padding:30px;
border-radius:18px;
text-align:center;

}}


.card {{

background:#111827;
padding:25px;
border-radius:15px;
margin-top:25px;

box-shadow:0 0 20px #000;

}}


.score {{

font-size:70px;
font-weight:bold;
text-align:center;
color:{color};

}}


.badge {{

text-align:center;
font-size:25px;
font-weight:bold;
color:{color};

}}


table {{

width:100%;
border-collapse:collapse;

}}


th {{

background:#1f2937;
color:#00d9ff;

}}


td,th {{

padding:12px;
border-bottom:1px solid #333;

}}


.open {{

color:#00ff88;
font-weight:bold;

}}


.closed {{

color:#ff5555;

}}


.high {{

color:#ff4444;

}}


.medium {{

color:#ffaa00;

}}


.low {{

color:#00ff88;

}}


.footer {{

margin-top:40px;
text-align:center;
color:#888;

}}

</style>


</head>


<body>


<div class="container">


<div class="header">

<h1>🛡 WebShield 2.0</h1>

<h2>Web Security Assessment Report</h2>

</div>



<div class="card">

<h2>📊 Security Overview</h2>


<p>
<b>Target:</b> {data.get("target")}
</p>


<p>
<b>Scan Time:</b> {datetime.now()}
</p>


<div class="score">

{score}/100

</div>


<div class="badge">

{rating} RISK

</div>


</div>





<div class="card">

<h2>🔐 Security Headers</h2>


<table>

<tr>

<th>Header</th>
<th>Status</th>
<th>Risk</th>

</tr>

"""


    for header,info in data.get("headers",{}).items():

        risk = info.get("risk","")


        html += f"""

<tr>

<td>{header}</td>

<td>{info.get("status")}</td>

<td class="{risk.lower()}">

{risk}

</td>

</tr>

"""


    html += """

</table>

</div>





<div class="card">

<h2>🔒 SSL / TLS Analysis</h2>


<table>

"""


    for key,value in data.get("ssl",{}).items():

        html += f"""

<tr>

<td>{key}</td>

<td>{value}</td>

</tr>

"""


    html += """

</table>

</div>





<div class="card">

<h2>🌐 DNS Information</h2>

<table>

"""


    for key,value in data.get("dns",{}).items():

        html += f"""

<tr>

<td>{key}</td>

<td>{value}</td>

</tr>

"""


    html += """

</table>

</div>





<div class="card">

<h2>🚪 Network Exposure</h2>


<table>

<tr>

<th>Port</th>

<th>Service</th>

<th>Status</th>

</tr>

"""


    for port in data.get("ports",[]):

        status = port.get("status")

        css = "open" if status=="OPEN" else "closed"


        html += f"""

<tr>

<td>{port.get("port")}</td>

<td>{port.get("service")}</td>

<td class="{css}">

{status}

</td>

</tr>

"""


    html += """

</table>

</div>





<div class="card">

<h2>⚙ Technology Detection</h2>

<ul>

"""


    for tech in data.get("technology",[]):

        if isinstance(tech,dict):

            html += f"<li>{tech.get('type')} : {tech.get('value')}</li>"

        else:

            html += f"<li>{tech}</li>"



    html += """

</ul>

</div>





<div class="footer">

Generated by WebShield 2.0<br>

Web Security Assessment Framework

</div>


</div>


</body>

</html>

"""



    with open(
        f"reports/{filename}.html",
        "w"
    ) as file:

        file.write(html)


    print(
        "[+] Professional HTML Report Generated"
    )
